name: Staging - Build and deploy Project Zoe client

on:
  push:
    branches: [ develop ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install   
          
      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
          
      - name: Create an .env file
        env:
          STAGING_ENV_FILE: ${{ secrets.STAGING_ENV_FILE }}
        run: |
          echo $STAGING_ENV_FILE | base64 --decode > ./.env
      
      # Temporarily skip eslint by using DISABLE_ESLINT_PLUGIN
      - name: Build
        run: |
          DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DO_PRIVATE_KEY" > ~/.ssh/project-zoe-prod-1.key
          chmod 600 ~/.ssh/project-zoe-prod-1.key
          cat >>~/.ssh/config <<END
          Host project-zoe-prod-1
            HostName $DO_HOST
            User $DO_USERNAME
            IdentityFile ~/.ssh/project-zoe-prod-1.key
            StrictHostKeyChecking no
          END
        env:
          DO_USERNAME: ${{ secrets.DO_USERNAME }}
          DO_PRIVATE_KEY: ${{ secrets.DO_PRIVATE_KEY }}
          DO_HOST: ${{ secrets.DO_HOST }}

      - name: Deploy the app
        run: rsync -rtvO ./build/ project-zoe-prod-1:/opt/staging/project-zoe-client/build/
            
 
